# SPDX-License-Identifier: Apache-2.0
# docs/gallery.md is generated by tools/gallery/main.cpp and checked in, so
# that a reader browsing GitHub sees the page without building anything, and a
# diff shows when a formula's rendering changes. This test is what keeps that
# promise honest: it regenerates the page into a temporary file and compares
# it against the checked-in copy.
#
# The comparison is line-ending-insensitive, not byte for byte: CMake's
# file(READ) normalises CRLF to LF, and the generator (tools/gallery/main.cpp)
# opens its output stream in text mode, so a Windows build writes CRLF while
# the checked-in file is LF (.gitattributes: `* text=auto eol=lf`). That is
# the right comparison here -- the content this check exists to keep honest
# is the Markdown text, not its line endings, and git already normalises a
# Windows regeneration back to LF on commit, so a byte-for-byte check would
# fail a rebuild that changed nothing a reader or a diff would ever see.

execute_process(
    COMMAND "${GALLERY_EXE}" "${BINARY_DIR}/gallery-regenerated.md"
    RESULT_VARIABLE galleryResult
    OUTPUT_VARIABLE galleryOut
    ERROR_VARIABLE galleryErr)

if(NOT galleryResult EQUAL 0)
    message(FATAL_ERROR
        "gallery.is-current: the generator itself failed (exit ${galleryResult}).\n"
        "--- stdout ---\n${galleryOut}\n--- stderr ---\n${galleryErr}")
endif()

if(NOT EXISTS "${EXPECTED_FILE}")
    message(FATAL_ERROR "gallery.is-current: ${EXPECTED_FILE} does not exist")
endif()

file(READ "${BINARY_DIR}/gallery-regenerated.md" regeneratedContent)
file(READ "${EXPECTED_FILE}" expectedContent)

if(NOT regeneratedContent STREQUAL expectedContent)
    message(FATAL_ERROR
        "docs/gallery.md is stale: regenerating it produces a different file than what is "
        "checked in. Regenerate it and commit the result:\n\n"
        "    \"${GALLERY_EXE}\" \"${EXPECTED_FILE}\"\n")
endif()

message(STATUS "docs/gallery.md is current")
